// Generated by CoffeeScript 1.8.0
(function() {
  var NameRandomizerDynamicValue;

  NameRandomizerDynamicValue = function() {
    this.maleNames = [
      "Sleve",
      "Onson",
      "Darryl",
      "Anatoli",
      "Rey",
      "Glenallen",
      "Mario",
      "Raul",
      "Kevin",
      "Tony",
      "Bobson",
      "Willie",
      "Jeromy",
      "Scott",
      "Shown",
      "Dean",
      "Mike",
      "Dwigt",
      "Tim",
      "Karl",
      "Todd"
];

this.lastNames = [
  "McDichael",
  "Sweemey",
  "Archideld",
  "Smorin",
  "Mcsriff",
  "Mixon",
  "Mcrlwain",
  "Chamgerlain",
  "Nogilny",
  "Smehrik",
  "Dugnutt",
  "Dustice",
  "Gride",
  "Dourque",
  "Furcotte",
  "Wesrey",
  "Truk",
  "Rortugal",
  "Sandaele",
  "Dandleton",
  "Sernandez",
  "Bonzalez"
];

    this.evaluate = function() {
      var array = [];
      if (this.arrayType == "maleNames") {
        array = this.maleNames;
      }
      else if (this.arrayType == "lastNames") {
        array = this.lastNames;
      }
      else {
        array = ["Choose either `maleNames` or `lastNames`"];
      }

      var name_idx = Math.floor(Math.random() * array.length);
      return "" + array[name_idx];
    };
    this.title = function() {
      return "Name Randomizer";
    };
  };

  NameRandomizerDynamicValue.identifier = "com.commanigy.PawExtensions.NameRandomizerDynamicValue";

  NameRandomizerDynamicValue.title = "Name Randomizer Dynamic Value";

  NameRandomizerDynamicValue.inputs = [
    DynamicValueInput("arrayType", "Type", "String")
  ];

  registerDynamicValueClass(NameRandomizerDynamicValue);

}).call(this);
